package com.trevora.api.features.sharing;


import com.trevora.api.features.auth.CurrentUserService;
import com.trevora.api.features.servicerecord.ServiceRecord;
import com.trevora.api.features.vehicle.VehicleService;
import com.trevora.api.features.sharing.CreateMechanicAccessRequest;
import com.trevora.api.features.sharing.CreateQRAccessRequest;
import com.trevora.api.features.sharing.MechanicAccessRequestResponse;
import com.trevora.api.features.sharing.MechanicAccessSessionResponse;
import com.trevora.api.features.sharing.PublicMechanicRequestStatusResponse;
import com.trevora.api.features.sharing.PublicQRAccessRequestResponse;
import com.trevora.api.features.sharing.QRAccessRequestResponse;
import com.trevora.api.shared.exception.AccessRequestException;
import com.trevora.api.shared.exception.ResourceNotFoundException;
import com.trevora.api.features.sharing.MechanicAccessRequest;
import com.trevora.api.features.sharing.QRAccessRequest;
import com.trevora.api.features.vehicle.VehicleProfile;
import com.trevora.api.features.sharing.MechanicAccessRepository;
import com.trevora.api.features.mechanicaccess.MechanicAccessSessionRepository;
import com.trevora.api.features.sharing.QRAccessRepository;
import com.trevora.api.features.servicerecord.ServiceRecordRepository;
import com.trevora.api.features.vehicle.VehicleRepository;
import java.security.SecureRandom;
import java.time.Instant;
import java.util.Base64;
import java.util.List;
import java.util.UUID;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class QRAccessService {
    public static final String STATUS_ACTIVE = "ACTIVE";
    public static final String STATUS_REQUESTED = "REQUESTED";
    public static final String STATUS_APPROVED = "APPROVED";
    public static final String STATUS_DENIED = "DENIED";
    public static final String STATUS_EXPIRED = "EXPIRED";

    private static final SecureRandom TOKEN_RANDOM = new SecureRandom();

    private final QRAccessRepository qrAccessRepository;
    private final MechanicAccessRepository mechanicAccessRepository;
    private final MechanicAccessSessionRepository sessionRepository;
    private final ServiceRecordRepository serviceRecordRepository;
    private final VehicleRepository vehicleRepository;
    private final VehicleService vehicleService;
    private final CurrentUserService currentUserService;
    private final String frontendBaseUrl;

    public QRAccessService(
            QRAccessRepository qrAccessRepository,
            MechanicAccessRepository mechanicAccessRepository,
            MechanicAccessSessionRepository sessionRepository,
            ServiceRecordRepository serviceRecordRepository,
            VehicleRepository vehicleRepository,
            VehicleService vehicleService,
            CurrentUserService currentUserService,
            @Value("${trevora.frontend-base-url:}") String frontendBaseUrl,
            @Value("${trevora.cors.allowed-origins:}") String corsAllowedOrigins
    ) {
        this.qrAccessRepository = qrAccessRepository;
        this.mechanicAccessRepository = mechanicAccessRepository;
        this.sessionRepository = sessionRepository;
        this.serviceRecordRepository = serviceRecordRepository;
        this.vehicleRepository = vehicleRepository;
        this.vehicleService = vehicleService;
        this.currentUserService = currentUserService;
        this.frontendBaseUrl = resolveFrontendBaseUrl(frontendBaseUrl, corsAllowedOrigins);
    }

    /**
     * Where the QR code should point.
     *
     * <p>This is the address a mechanic's phone opens, so it has to be the
     * browser app's origin -- not the API's, and emphatically not this
     * process's idea of localhost. It was defaulted to
     * {@code http://localhost:5173} and configured nowhere, which meant every
     * code generated by the deployed API pointed at a machine the scanner does
     * not have. The link worked perfectly in development and could not work at
     * all anywhere else.
     *
     * <p>Three sources, in order:
     *
     * <ol>
     *   <li>{@code TREVORA_FRONTEND_BASE_URL}, when someone has set it.</li>
     *   <li>Otherwise the first entry of {@code TREVORA_CORS_ALLOWED_ORIGINS}.
     *       That variable already has to name the browser app's origin for the
     *       app to function at all, so deriving from it means a deployment
     *       cannot be half-configured: if the frontend can call the API, the
     *       QR codes point somewhere real. Wildcard and localhost patterns are
     *       skipped -- they are development conveniences, not addresses.</li>
     *   <li>Failing both, the development default.</li>
     * </ol>
     */
    private static String resolveFrontendBaseUrl(String configured, String corsAllowedOrigins) {
        if (configured != null && !configured.isBlank()) {
            return configured.trim();
        }

        for (String origin : (corsAllowedOrigins == null ? "" : corsAllowedOrigins).split(",")) {
            String candidate = origin.trim();
            if (candidate.isEmpty() || candidate.contains("*")) {
                continue;
            }
            if (candidate.startsWith("http://localhost") || candidate.startsWith("http://127.0.0.1")) {
                continue;
            }
            return candidate;
        }

        return "http://localhost:5173";
    }

    /** The lifetimes screens state. Public: the Terms and Privacy pages state them before sign-in. */
    public SharingPolicyResponse getSharingPolicy() {
        return SharingPolicyResponse.current();
    }

    @Transactional
    public QRAccessRequestResponse createAccessRequest(CreateQRAccessRequest request) {
        currentUserService.requireVehicleOwner();
        if (request.vehicleProfileId() == null) {
            throw new AccessRequestException("vehicleProfileId is required.");
        }

        VehicleProfile vehicle = vehicleService.verifyVehicleBelongsToCurrentUser(request.vehicleProfileId());
        UUID ownerId = currentUserService.getCurrentUserId();
        Instant now = Instant.now();

        List<QRAccessRequest> live = liveUnscannedLinks(vehicle.getVehicleId(), ownerId, now);
        QRAccessRequest qrRequest;
        if (live.isEmpty()) {
            qrRequest = new QRAccessRequest();
            qrRequest.setVehicleId(vehicle.getVehicleId());
            qrRequest.setOwnerId(ownerId);
        } else {
            qrRequest = live.get(0);
            /* Only possible for links made before overwriting existed, when each
               click added a row. They stop working now so one code is live, and
               the rows stay: they are the record that access was offered. */
            for (QRAccessRequest older : live.subList(1, live.size())) {
                older.setStatus(STATUS_EXPIRED);
                older.setExpiresAt(now);
                qrAccessRepository.save(older);
            }
        }
        qrRequest.setAccessToken(uniqueToken());
        qrRequest.setStatus(STATUS_ACTIVE);
        qrRequest.setExpiresAt(now.plus(SharingPolicy.LINK_LIFETIME));

        QRAccessRequest saved = qrAccessRepository.save(qrRequest);
        return toOwnerResponse(saved);
    }

    /**
     * The vehicle's links that a new one should overwrite, newest first.
     *
     * <p>Generating again used to insert a row every time, so tapping the
     * button grew the list without limit. A link nobody has scanned yet is
     * still just an offer, so generating again reuses that row -- new token,
     * new expiry -- instead of adding one. Rows are never deleted: the request
     * and session tables cascade from this one, and a link is the record that
     * access was offered at a given time.
     *
     * <p>Live and unscanned means all of these:
     * <ul>
     *   <li>{@code ACTIVE}. Anything else has been scanned, decided or expired.</li>
     *   <li>Not past its expiry. The status column is not trusted for this: the
     *       owner's list computes expiry on a read-only transaction, so a lapsed
     *       link can still say ACTIVE in the table.</li>
     *   <li>Never used, and no mechanic request points at it. Either would
     *       mean a mechanic scanned it, and that row is an access event that
     *       stays exactly as it is -- as does any session approved from it,
     *       whose lifetime is its own.</li>
     * </ul>
     */
    private List<QRAccessRequest> liveUnscannedLinks(UUID vehicleId, UUID ownerId, Instant now) {
        return qrAccessRepository
                .findByVehicleIdAndOwnerIdOrderByCreatedAtDesc(vehicleId, ownerId)
                .stream()
                .filter(link -> STATUS_ACTIVE.equals(link.getStatus()))
                .filter(link -> link.getExpiresAt() != null && link.getExpiresAt().isAfter(now))
                .filter(link -> link.getUsedAt() == null)
                .filter(link -> !mechanicAccessRepository.existsByQrAccessRequestId(link.getQrAccessRequestId()))
                .toList();
    }

    @Transactional(readOnly = true)
    public List<QRAccessRequestResponse> getVehicleAccessRequests(UUID vehicleId) {
        currentUserService.requireVehicleOwner();
        vehicleService.verifyVehicleBelongsToCurrentUser(vehicleId);
        UUID ownerId = currentUserService.getCurrentUserId();
        /* One count for the whole list. Every link here belongs to the same
           vehicle, so the number is the same on every row; counting it per link
           cost a query for each one. */
        long confirmedRecords = serviceRecordRepository.countByVehicleIdAndOwnerId(vehicleId, ownerId);
        return qrAccessRepository
                .findByVehicleIdAndOwnerIdOrderByCreatedAtDesc(vehicleId, ownerId)
                .stream()
                .map(link -> toOwnerResponse(link, confirmedRecords))
                .toList();
    }

    @Transactional
    public PublicQRAccessRequestResponse getPublicRequest(String token) {
        QRAccessRequest request = getValidTokenRequest(token);
        VehicleProfile vehicle = vehicleRepository.findById(request.getVehicleId())
                .orElseThrow(() -> new ResourceNotFoundException("Shared vehicle was not found."));
        return new PublicQRAccessRequestResponse(
                request.getQrAccessRequestId(),
                request.getVehicleId(),
                vehicleLabel(vehicle),
                request.getStatus(),
                request.getExpiresAt(),
                serviceRecordRepository.countByVehicleIdAndOwnerId(request.getVehicleId(), request.getOwnerId())
        );
    }

    @Transactional
    public MechanicAccessRequestResponse createMechanicRequest(String token, CreateMechanicAccessRequest request) {
        QRAccessRequest qrRequest = getValidTokenRequest(token);
        if (mechanicAccessRepository.existsByQrAccessRequestIdAndStatus(qrRequest.getQrAccessRequestId(), AccessApprovalService.REQUEST_PENDING)) {
            throw new AccessRequestException("A mechanic access request is already waiting for owner approval.");
        }
        if (mechanicAccessRepository.existsByQrAccessRequestIdAndStatus(qrRequest.getQrAccessRequestId(), STATUS_APPROVED)) {
            throw new AccessRequestException("This share link already has approved mechanic access.");
        }

        MechanicAccessRequest accessRequest = new MechanicAccessRequest();
        accessRequest.setQrAccessRequestId(qrRequest.getQrAccessRequestId());
        accessRequest.setVehicleId(qrRequest.getVehicleId());
        accessRequest.setOwnerId(qrRequest.getOwnerId());
        accessRequest.setMechanicId(null);
        accessRequest.setMechanicName(requiredText(request.mechanicName(), "mechanicName"));
        accessRequest.setShopName(blankToNull(request.shopName()));
        accessRequest.setContactInfo(blankToNull(request.contactInfo()));
        accessRequest.setReason(blankToNull(request.reason()));
        accessRequest.setStatus(AccessApprovalService.REQUEST_PENDING);
        accessRequest.setRequestedAt(Instant.now());

        qrRequest.setStatus(STATUS_REQUESTED);
        qrRequest.setUsedAt(Instant.now());
        qrAccessRepository.save(qrRequest);

        MechanicAccessRequest saved = mechanicAccessRepository.save(accessRequest);
        VehicleProfile vehicle = vehicleRepository.findById(saved.getVehicleId())
                .orElseThrow(() -> new ResourceNotFoundException("Shared vehicle was not found."));
        return MechanicAccessRequestResponse.from(saved, vehicleLabel(vehicle));
    }

    @Transactional
    public PublicMechanicRequestStatusResponse getMechanicRequestStatus(String token) {
        QRAccessRequest qrRequest = qrAccessRepository.findByAccessToken(token)
                .orElseThrow(() -> new ResourceNotFoundException("Access link was not found."));
        qrRequest = expireIfNeeded(qrRequest);
        PublicQRAccessRequestResponse publicRequest = toPublicResponse(qrRequest);
        MechanicAccessRequestResponse mechanicRequest = mechanicAccessRepository
                .findFirstByQrAccessRequestIdOrderByRequestedAtDesc(qrRequest.getQrAccessRequestId())
                .map(request -> {
                    VehicleProfile vehicle = vehicleRepository.findById(request.getVehicleId())
                            .orElseThrow(() -> new ResourceNotFoundException("Shared vehicle was not found."));
                    return MechanicAccessRequestResponse.from(request, vehicleLabel(vehicle));
                })
                .orElse(null);
        MechanicAccessSessionResponse session = mechanicRequest == null ? null : sessionRepository
                .findByMechanicAccessRequestId(mechanicRequest.mechanicAccessRequestId())
                .map(accessSession -> MechanicAccessSessionResponse.from(accessSession, vehicleLabel(accessSession.getVehicleId())))
                .orElse(null);

        return new PublicMechanicRequestStatusResponse(publicRequest, mechanicRequest, session);
    }

    QRAccessRequest getOwnerScopedQrRequest(UUID requestId, UUID ownerId) {
        QRAccessRequest request = qrAccessRepository.findById(requestId)
                .orElseThrow(() -> new ResourceNotFoundException("QR access request was not found."));
        if (!ownerId.equals(request.getOwnerId())) {
            throw new AccessRequestException("This access request does not belong to the current owner.");
        }
        return request;
    }

    QRAccessRequest expireIfNeeded(QRAccessRequest request) {
        if (!STATUS_EXPIRED.equals(request.getStatus()) && request.getExpiresAt().isBefore(Instant.now())) {
            request.setStatus(STATUS_EXPIRED);
            return qrAccessRepository.save(request);
        }
        return request;
    }

    String vehicleLabel(UUID vehicleId) {
        return vehicleRepository.findById(vehicleId)
                .map(this::vehicleLabel)
                .orElse("Selected vehicle");
    }

    private QRAccessRequest getValidTokenRequest(String token) {
        QRAccessRequest request = qrAccessRepository.findByAccessToken(token)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "This access link has expired or been replaced by a newer one. Ask the owner for a new code."));
        request = expireIfNeeded(request);
        if (STATUS_EXPIRED.equals(request.getStatus())) {
            throw new AccessRequestException("This access link has expired.");
        }
        if (STATUS_DENIED.equals(request.getStatus())) {
            throw new AccessRequestException("This access link was denied by the owner.");
        }
        if (STATUS_APPROVED.equals(request.getStatus())) {
            throw new AccessRequestException("This access link has already been approved.");
        }
        return request;
    }

    private QRAccessRequestResponse toOwnerResponse(QRAccessRequest request) {
        return toOwnerResponse(
                request,
                serviceRecordRepository.countByVehicleIdAndOwnerId(request.getVehicleId(), request.getOwnerId())
        );
    }

    private QRAccessRequestResponse toOwnerResponse(QRAccessRequest request, long confirmedRecords) {
        QRAccessRequest current = expireIfNeeded(request);
        return QRAccessRequestResponse.from(current, accessUrl(current.getAccessToken()), confirmedRecords);
    }

    private PublicQRAccessRequestResponse toPublicResponse(QRAccessRequest request) {
        VehicleProfile vehicle = vehicleRepository.findById(request.getVehicleId())
                .orElseThrow(() -> new ResourceNotFoundException("Shared vehicle was not found."));
        return new PublicQRAccessRequestResponse(
                request.getQrAccessRequestId(),
                request.getVehicleId(),
                vehicleLabel(vehicle),
                request.getStatus(),
                request.getExpiresAt(),
                serviceRecordRepository.countByVehicleIdAndOwnerId(request.getVehicleId(), request.getOwnerId())
        );
    }

    private String uniqueToken() {
        String token;
        do {
            byte[] bytes = new byte[24];
            TOKEN_RANDOM.nextBytes(bytes);
            token = Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);
        } while (qrAccessRepository.findByAccessToken(token).isPresent());
        return token;
    }

    private String accessUrl(String token) {
        return frontendBaseUrl.replaceAll("/+$", "") + "/access/request/" + token;
    }

    private String vehicleLabel(VehicleProfile vehicle) {
        if (vehicle.getNickname() != null && !vehicle.getNickname().isBlank()) {
            return vehicle.getNickname();
        }
        StringBuilder label = new StringBuilder();
        if (vehicle.getYear() != null) {
            label.append(vehicle.getYear());
        }
        appendLabelPart(label, vehicle.getMake());
        appendLabelPart(label, vehicle.getModel());
        return label.isEmpty() ? "Selected vehicle" : label.toString();
    }

    private void appendLabelPart(StringBuilder label, String value) {
        if (value == null || value.isBlank()) {
            return;
        }
        if (!label.isEmpty()) {
            label.append(' ');
        }
        label.append(value.trim());
    }

    private String requiredText(String value, String fieldName) {
        String cleaned = blankToNull(value);
        if (cleaned == null) {
            throw new AccessRequestException(fieldName + " is required.");
        }
        return cleaned;
    }

    private String blankToNull(String value) {
        if (value == null || value.isBlank()) {
            return null;
        }
        return value.trim();
    }
}
