import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import {
  getPublicQRAccessRequest,
  getMechanicRequestStatus,
  submitMechanicAccessRequest,
} from '../api/qrAccess';

const DEMO_QR_TOKEN_KEY = 'trevora.demoMechanic.latestQrToken';
const DEMO_SESSION_ID_KEY = 'trevora.demoMechanic.approvedSessionId';

function formatDateTime(value) {
  if (!value) return 'Not available';
  return new Date(value).toLocaleString();
}

export default function MechanicPlaceholderPage() {
  const [token] = useState(() => window.localStorage.getItem(DEMO_QR_TOKEN_KEY) || '');
  const [shareRequest, setShareRequest] = useState(null);
  const [submittedRequest, setSubmittedRequest] = useState(null);
  const [approvedSession, setApprovedSession] = useState(null);
  const [showRequestModal, setShowRequestModal] = useState(Boolean(token));
  const [form, setForm] = useState({
    mechanicName: 'Juan Santos',
    shopName: 'Superior Auto Repairs',
    contactInfo: '+63 917 123 4567',
    reason: 'Checking this vehicle service history before maintenance.',
  });
  const [loading, setLoading] = useState(Boolean(token));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState('');

  useEffect(() => {
    if (!token) return undefined;
    let active = true;
    setLoading(true);
    setError('');

    loadDemoMechanicStatus(token)
      .then((statusData) => {
        if (!active) return;
        setShareRequest(statusData.qrRequest);
        if (statusData.mechanicRequest) {
          setSubmittedRequest(statusData.mechanicRequest);
          setShowRequestModal(false);
        }
        if (statusData.session) {
          setApprovedSession(statusData.session);
          window.localStorage.setItem(DEMO_SESSION_ID_KEY, statusData.session.mechanicAccessSessionId);
        }
      })
      .catch((err) => {
        if (active) setError(err.message);
      })
      .finally(() => {
        if (active) setLoading(false);
      });

    return () => {
      active = false;
    };
  }, [token]);

  useEffect(() => {
    if (!token || !submittedRequest || approvedSession) return undefined;

    const intervalId = window.setInterval(() => {
      getMechanicRequestStatus(token)
        .then((status) => {
          if (status.mechanicRequest) setSubmittedRequest(status.mechanicRequest);
          if (status.session) {
            setApprovedSession(status.session);
            window.localStorage.setItem(DEMO_SESSION_ID_KEY, status.session.mechanicAccessSessionId);
          }
        })
        .catch(() => {});
    }, 3000);

    return () => window.clearInterval(intervalId);
  }, [approvedSession, submittedRequest, token]);

  function updateField(event) {
    const { name, value } = event.target;
    setForm((current) => ({ ...current, [name]: value }));
  }

  async function loadDemoMechanicStatus(currentToken) {
    try {
      return await getMechanicRequestStatus(currentToken);
    } catch (err) {
      const qrRequest = await getPublicQRAccessRequest(currentToken);
      return {
        qrRequest,
        mechanicRequest: null,
        session: null,
      };
    }
  }

  async function handleSubmit(event) {
    event.preventDefault();
    setSaving(true);
    setError('');

    try {
      const request = await submitMechanicAccessRequest(token, form);
      setSubmittedRequest(request);
      setShowRequestModal(false);
    } catch (err) {
      setError(err.message);
    } finally {
      setSaving(false);
    }
  }

  if (!token) {
    return (
      <main className="page-shell">
        <section className="page-header">
          <p className="eyebrow">Mechanic Demo</p>
          <h1>Waiting for a QR link</h1>
          <p>Generate a QR/share access request as Demo Vehicle Owner first, then switch back to Demo Mechanic.</p>
        </section>

        <section className="history-empty-state">
          <h2>No scanned vehicle yet</h2>
          <p>The demo mechanic picks up the most recent QR access link generated by the owner.</p>
          <Link className="button-link" to="/dashboard">
            Back to dashboard
          </Link>
        </section>
      </main>
    );
  }

  return (
    <main className="page-shell module-four-page">
      <section className="mechanic-landing-hero">
        <p className="eyebrow">Mechanic Demo</p>
        <h1>{shareRequest ? shareRequest.vehicleLabel : 'Scanned vehicle link'}</h1>
        <p>The QR scan opens this mechanic page. Submit identity details so the owner can approve read-only access.</p>
      </section>

      {loading && <p className="muted">Checking scanned QR link...</p>}
      {error && <div className="alert">{error}</div>}

      {!loading && shareRequest && (
        <>
          <section className="mechanic-dashboard-grid">
            <article className="mechanic-dashboard-card primary">
              <span className="badge subtle">Shared vehicle</span>
              <h2>{shareRequest.vehicleLabel}</h2>
              <p>{shareRequest.plateNumber || 'Plate number not provided'}</p>
              <dl className="compact-facts">
                <div>
                  <dt>Status</dt>
                  <dd>{shareRequest.status}</dd>
                </div>
                <div>
                  <dt>Expires</dt>
                  <dd>{formatDateTime(shareRequest.expiresAt)}</dd>
                </div>
                <div>
                  <dt>Confirmed records in scope</dt>
                  <dd>{shareRequest.confirmedRecordCount}</dd>
                </div>
              </dl>
              <div className="access-scope-box">
                <strong>Read-only after approval</strong>
                <p>The owner must approve this request before any service history can be viewed.</p>
              </div>
            </article>

            <article className="mechanic-dashboard-card">
              <h2>Access status</h2>
              {!submittedRequest && (
                <>
                  <p>No request has been sent yet.</p>
                  <button type="button" onClick={() => setShowRequestModal(true)}>
                    Open request form
                  </button>
                </>
              )}
              {submittedRequest && !approvedSession && (
                <>
                  <span className="access-status access-status-pending">{submittedRequest.status}</span>
                  <p>Your request was sent. Switch to Demo Vehicle Owner, open Shared Access → Requests, and approve it.</p>
                  <button className="button-secondary" type="button" onClick={() => window.location.reload()}>
                    Refresh status
                  </button>
                </>
              )}
              {approvedSession && (
                <>
                  <span className="access-status access-status-approved">APPROVED</span>
                  <p>Temporary read-only access is ready for this vehicle.</p>
                  <Link className="button-link" to={`/mechanic/access/${approvedSession.mechanicAccessSessionId}`}>
                    View service history
                  </Link>
                </>
              )}
            </article>
          </section>

          {showRequestModal && !submittedRequest && (
            <div className="modal-backdrop">
              <section className="mechanic-request-modal" role="dialog" aria-modal="true" aria-labelledby="request-title">
                <div className="access-card-header">
                  <div>
                    <p className="eyebrow">Mechanic Request</p>
                    <h2 id="request-title">Request temporary access</h2>
                    <p>These details help the owner verify who is asking to view the vehicle history.</p>
                  </div>
                  <button className="icon-close-button" type="button" onClick={() => setShowRequestModal(false)}>
                    x
                  </button>
                </div>
                <form className="auth-form" onSubmit={handleSubmit}>
                  <label>
                    Mechanic name
                    <input name="mechanicName" value={form.mechanicName} onChange={updateField} required autoFocus />
                  </label>
                  <label>
                    Shop name
                    <input name="shopName" value={form.shopName} onChange={updateField} />
                  </label>
                  <label>
                    Contact info
                    <input name="contactInfo" value={form.contactInfo} onChange={updateField} />
                  </label>
                  <label>
                    Reason for access
                    <textarea name="reason" value={form.reason} onChange={updateField} rows="4" />
                  </label>
                  <button type="submit" disabled={saving}>
                    {saving ? 'Sending request...' : 'Submit access request'}
                  </button>
                </form>
              </section>
            </div>
          )}
        </>
      )}
    </main>
  );
}
